// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_SprintAPI_Escola.Data;

#nullable disable

namespace WebAPI_SprintAPI_Escola.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAluno"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdAluno");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.AlunoResponsavel", b =>
                {
                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("int");

                    b.HasKey("IdAluno", "IdResponsavel");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("AlunosResponsaveis");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.AlunoTurma", b =>
                {
                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdTurma")
                        .HasColumnType("int");

                    b.HasKey("IdAluno", "IdTurma");

                    b.HasIndex("IdTurma");

                    b.ToTable("AlunosTurmas");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Disciplina", b =>
                {
                    b.Property<int>("IdDisciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDisciplina"));

                    b.Property<int>("IdTurma")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TurmaIdTurma")
                        .HasColumnType("int");

                    b.HasKey("IdDisciplina");

                    b.HasIndex("TurmaIdTurma");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Nota", b =>
                {
                    b.Property<int>("IdNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNota"));

                    b.Property<int>("AlunoIdAluno")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaIdDisciplina")
                        .HasColumnType("int");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int");

                    b.Property<int>("IdTurma")
                        .HasColumnType("int");

                    b.Property<int>("TurmaIdTurma")
                        .HasColumnType("int");

                    b.Property<int>("Unidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorNota")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdNota");

                    b.HasIndex("AlunoIdAluno");

                    b.HasIndex("DisciplinaIdDisciplina");

                    b.HasIndex("TurmaIdTurma");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Professor", b =>
                {
                    b.Property<int>("IdProfessor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProfessor"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdProfessor");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.ProfessorDisciplina", b =>
                {
                    b.Property<int>("IdProfessor")
                        .HasColumnType("int");

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int");

                    b.HasKey("IdProfessor", "IdDisciplina");

                    b.HasIndex("IdDisciplina");

                    b.ToTable("ProfessoresDisciplinas");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Responsavel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdResponsavel"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdResponsavel");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Turma", b =>
                {
                    b.Property<int>("IdTurma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTurma"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTurma");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.AlunoResponsavel", b =>
                {
                    b.HasOne("WebAPI_SprintAPI_Escola.Models.Aluno", "Aluno")
                        .WithMany("AlunoResponsaveis")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI_SprintAPI_Escola.Models.Responsavel", "Responsavel")
                        .WithMany("AlunoResponsaveis")
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.AlunoTurma", b =>
                {
                    b.HasOne("WebAPI_SprintAPI_Escola.Models.Aluno", "Aluno")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI_SprintAPI_Escola.Models.Turma", "Turma")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Disciplina", b =>
                {
                    b.HasOne("WebAPI_SprintAPI_Escola.Models.Turma", "Turma")
                        .WithMany("Disciplinas")
                        .HasForeignKey("TurmaIdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Nota", b =>
                {
                    b.HasOne("WebAPI_SprintAPI_Escola.Models.Aluno", "Aluno")
                        .WithMany("Notas")
                        .HasForeignKey("AlunoIdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI_SprintAPI_Escola.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaIdDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI_SprintAPI_Escola.Models.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaIdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.ProfessorDisciplina", b =>
                {
                    b.HasOne("WebAPI_SprintAPI_Escola.Models.Disciplina", "Disciplina")
                        .WithMany("ProfessorDisciplinas")
                        .HasForeignKey("IdDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI_SprintAPI_Escola.Models.Professor", "Professor")
                        .WithMany("ProfessorDisciplinas")
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Aluno", b =>
                {
                    b.Navigation("AlunoResponsaveis");

                    b.Navigation("AlunoTurmas");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Disciplina", b =>
                {
                    b.Navigation("ProfessorDisciplinas");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Professor", b =>
                {
                    b.Navigation("ProfessorDisciplinas");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Responsavel", b =>
                {
                    b.Navigation("AlunoResponsaveis");
                });

            modelBuilder.Entity("WebAPI_SprintAPI_Escola.Models.Turma", b =>
                {
                    b.Navigation("AlunoTurmas");

                    b.Navigation("Disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
